vim.g.mapleader = " "

vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv")
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv")

vim.keymap.set('n', '<C-h>', '<C-w>h')
vim.keymap.set('n', '<C-j>', '<C-w>j')
vim.keymap.set('n', '<C-k>', '<C-w>k')
vim.keymap.set('n', '<C-l>', '<C-w>l')
vim.keymap.set('n', '<C-s>', ':w<CR>')
vim.keymap.set('n', '<C-S-s>', ':wa<CR>')

vim.keymap.set('n', 'J', 'mzJ`z')
vim.keymap.set('n', '<C-d>', '<C-d>zz')
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('n', '<leader>sa', ':%s/\\<<C-r><C-w>\\>//g<left><left>')
vim.keymap.set('n', '<leader>sq', ':%s/\\<<C-r><C-w>\\>//gc<left><left><left>')
vim.keymap.set('n', '<leader>sl', ':s/\\<<C-r><C-w>\\>//g<left><left>')
vim.keymap.set('n', "<leader>w'", "ciw''<ESC>P")
vim.keymap.set('n', '<leader>w"', 'ciw""<ESC>P')
vim.keymap.set('n', '<leader>w(', 'ciw()<ESC>P')
vim.keymap.set('n', '<leader>w{', 'ciw{}<ESC>P')
vim.keymap.set('n', '<leader>w[', 'ciw[]<ESC>P')
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
vim.keymap.set('n', '<leader>1', '1gt')
vim.keymap.set('n', '<leader>2', '2gt')
vim.keymap.set('n', '<leader>3', '3gt')
vim.keymap.set('n', '<leader>4', '4gt')
vim.keymap.set('n', '<leader>5', '5gt')
vim.keymap.set('n', '<leader>6', '6gt')
vim.keymap.set('n', '<leader>7', '7gt')
vim.keymap.set('n', '<leader>8', '8gt')
vim.keymap.set('n', '<leader>9', '9gt')
vim.keymap.set('n', '<leader>0', ':tablast<CR>')

vim.keymap.set('n', '<leader>tb', ':! just build<cr>')
vim.keymap.set('n', '<leader>tr', ':! just run<cr>')
